### ISSUE TITLE
Interface Rework

### ISSUE THREAD

**Issue by Garihosu** [sam-astro/Astro8-Computer#22]
This will either be a pull request or a fork.

Using Qt, the interface system will be reworked to hopefully make it windowed-only. This will help with MacOS .app bundling and making the application simple to use for people not familiar with the console. This will also expand upon debugging, for example, pausing, playing, frame-by-frame, and memory viewing. If you still wish to use the console command, then you still can.

And no, I am not doing this just for the purpose of Mac support, it's actually a feature that would be helpful for all the other platforms as well.

If I end up not being able to do this fully in C++, then I may make an emulator in Python or Java and see what I can do with that. If anybody want to help, then that would be nice, since it would give me motivation.

Thanks, everyone, and thanks @sam-astro for making a project that I actually have the passion to help for.

**Comment by sam-astro** [comment]
Thanks so much for contributing! This actually sounds like a really useful addition and would make for a much better ease of use.

**Comment by EmeraldCraft34** [comment]
The fork can be found here: https://github.com/EmeraldCraft34/Astro8-Computer

I may be slowed down a bit, because of school, but I'll try and fit it in.

**Comment by EmeraldCraft34** [comment]
I'll post my updates here since it's gonna take a while.

I've started migrating some of the functions and stuff into separate files to organize it better. For example, I'm putting the functions and variables for Armstrong into `compiler.cpp` and `compiler.hpp`. There will also be files for the VM, most likely called `vm.cpp` and `vm.hpp`. I'm probably going to turn the VM variables and functions into a class to make it easier to access and make it more organized.

Right now I have files for the conversion functions (ex. charToString) which is done, and files for the compiler which I'm still working on.

**Comment by Garihosu** [comment]
this has unfortunately been closed. i apologize, but this project would probably do better without my contribution.
