### ISSUE TITLE
`jmp` instruction is limited between 0-2047, so any programs longer than that fail

### ISSUE THREAD

**Issue by sam-astro** [sam-astro/Astro8-Computer#9]
**Describe the bug**
`jmp` instruction is limited between 0-2047, so any programs longer than that fail

A new `jmpl` instruction should be added for jumping to large addresses (larger than 2047). This will use the following word as an address, rather than the 11-bit instruction area.

**Comment by GerardSmit** [comment]
Currently `J` is always using the lowest 12 bits of the instruction:

https://github.com/sam-astro/Astro8-Computer/blob/37aeb324e9cb093936737815d9b344ca8d6d17bb/Astro8-Emulator/main.cpp#L594-L599

Even though all jump instructions (`JMP`, `JMPZ`, `JMPC`) are also executing micro instruction `IR` (setting the lowest 12 bits of the instruction to the bus):

https://github.com/sam-astro/Astro8-Computer/blob/37aeb324e9cb093936737815d9b344ca8d6d17bb/Astro8-Emulator/main.cpp#L140-L142

This seems like a bug in the emulator, since the README states that the bus should is used:

https://github.com/sam-astro/Astro8-Computer/blob/37aeb324e9cb093936737815d9b344ca8d6d17bb/README.md?plain=1#L104

If we fix the micro instruction `J` to use the bus instead, we can make a new instruction `JMPL`  that does the following:

1. _NOOP_
2. `CR` read value from counter to bus  
    `AW` write lowest 12 bits from bus to mem. addr. register
3. `RM` read from memory to bus at the address in mem addr. register  
    `J` write from bus to counter current value

**Comment by sam-astro** [comment]
Fixed in v0.2.0, thanks!
